COMMIT_MESSAGE_REGEX: /[A-Z]{2,6}-[0-9]{2,6} [\s\S]*
VALID_COMMIT_MESSAGE: Commit messages are OK!
INVALID_COMMIT_MESSAGE: Error, commit message/s below doesn't match regex /[A-Z]{2,6}-[0-9]{2,6} [\s\S]*/i (e.g. LNG-123 Implement toolbar)

PR_TITLE_REGEX: /[\s\S]*/i
OUTPUT_TITLE_FAIL: Commit message/s does not match required regex (e.g. LNG-123 Implement toolbar)
OUTPUT_TITLE_SUCCESS: Commit messages are OK ;)
SINGLE_OTHER_INVALID_MESSAGE: other message is invalid
MULTIPLE_OTHER_INVALID_MESSAGE: other messages are invalid
VALID_PULL_REQUEST_MESSAGE: Pull request title is OK (by default accepts any string)
INVALID_PULL_REQUEST_MESSAGE: Bad. Pull request title is invalid
